apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    sa-app-green: prometheus-green
    sa-telemetry-app-green: prometheus-green
  name: prometheus-green
  namespace: sa-telemetry
spec:
  endpoints:
  - interval: 10s
    port: prometheus
  namespaceSelector:
    matchNames:
    - sa-telemetry
  selector:
    matchLabels:
      sa-app: prometheus-green
